### ISSUE TITLE
Problems with CoordMode

### ISSUE THREAD

**Issue by rmvz** [berban/FindClick#1]
While testing this script I found out that everytime I call FindClick to search for an image CoordMode for Pixel and Mouse is being set to "Screen". Any command regarding Pixel and Mouse (for example PixelGetColor or MouseMove) that activates after the image search treats their coordinate mode as "Screen" for obtaining a pixel or moving the mouse, rather than "Relative" (which is usually the default) or any previously set CoordMode option, like "Client".

I made two short examples using MouseMove and PixelGetColor:

#### MouseMove

    #SingleInstance, Force
    #Include <FindClick>
    CoordMode, Mouse, Client
    Run, Notepad.exe
    Sleep, 2000
    MouseMove, 100, 100
    Sleep, 2000
    FindClick("\Test.png", "n")
    ;CoordMode, Mouse, Client
    MouseMove, 200, 200
    Return

In the above example CoordMode is set to Client before FindClick. Notepad is activated (and is automatically the active window) and MouseMove moves the mouse successfully to x100 y100 within notepad's window client. Though, when FindClick is called and the mouse is moved again I would've expected it to move to x200 y200 in notepad's window client but instead it moves to x200 y200 of my screen's coordinates. 

For the mouse to actually move to x200 y200 within notepad either CoordMode has to be set to Client again after FindClick (as is shown in code) or FindClick needs to be removed. This will indeed result in the mouse moving to x200 y200 within notepad rather than my screen.

MouseMove can be replaced by Click and it goes the same way.

#### PixelGetColor

    #SingleInstance, Force
    #Include <FindClick>
    CoordMode, Pixel, Client
    Run, Notepad.exe
    Sleep, 200
    PixelGetColor, Color, 100, 100, RGB
    Sleep, 200
    FindClick("\Test.png", "n")
    ;CoordMode, Pixel, Client
    PixelGetColor, Color2, 200, 200, RGB
    MsgBox, PixelGetColor 1: %Color%`nPixelGetColor 2: %Color2%`n(after FindClick)
    Return

The above example is very much like the MouseMove example. Again notepad is activated and PixelGetColor successfully retrieves the color at x100 y100 within notepad's window client (0xFFFFFF). Though again, after FindClick PixelGetColor no longer searches for the color at x200 y200 within notepad but at x200 y200 of my screen, which does not result in 0xFFFFFF, which it should've been had it retrieved the color within notepad.

This can again be made working by either setting CoordMode back to Client or removing FindClick which will result in both PixelGetColor successfully retrieving the color from notepad's window client (2x 0xFFFFFF).

I tried both of the above examples out with "Relative" instead of "Client" as well and the same problem occurs.

Can you tell me if this is actually something that shouldn't happen or that I'm maybe just doing something wrong?

**Comment by berban** [comment]
Hey rmvz! Thanks for the bug report. Sorry I didn’t respond sooner but I only just now saw your comment. I don’t normally use GitHub and I guess it wasn’t set to give me email notifications. I'm on my way to work at the moment but I'll take a further look at your example tonight or later this week.

**Comment by berban** [comment]
Ok wow your comment is very simple haha. So apparently when I change coordmoode inside FindClick I never set it back to whatever it was to start the thread. That’s a very simple oversight on my part and I’ll post an update right away.

**Comment by rmvz** [comment]
Thanks a lot for looking into it and taking the time to resolve the issue. 👍

**Comment by berban** [comment]
Thanks for your patience, sorry it's been a busy week. I made the update. It should address the issue.

By the way I remembered the reason it was like that in the first place was because A_CoordModeMouse, A_CoordModePixel, etc didn't exist as variables when I first made this script. I always thought that was odd and I'm glad Lexikos and the community has added them.

**Comment by rmvz** [comment]
I have just tested my examples again with the updated version and can confirm that both CoordMode get successfully set back to what they were prior to calling FindClick. This was exactly the issue and you've fixed it, thanks a lot. 😄
